### ISSUE TITLE
Update README to actually say what this tool does

### ISSUE THREAD

**Issue by Sneethan** [Fisheiyy/dbm-discord-bot-updater#3]
This tool sounds cool, but it doesn't say what it does (converts embeds to send message, updates actions/node modules etc) Some clarification around this would be nice.

**Comment by Fisheiyy** [comment]
https://github.com/Fisheiyy/dbm-discord-bot-updater/commit/cbbf265f379cb95d5b11147d0df9a5eadfe1f4e1
